// En la listo enestas du tipoj de vortoj:
//
// - Vortoj finiĝantaj per streketo bezonas vortoklasan finaĵon (-o, -a, -i, -e)
// - Vortoj sen streketoj estas uzeblaj sen finaĵo
//
// La listo de landoj estis unue prenita de la oficiala listo de landnomoj de la
// Akademio de Esperanto (konsltebla sube).
// https://www.akademio-de-esperanto.org/decidoj/landnomoj/listo_de_rekomendataj_landnomoj/
// 
// Poste, ĝi estis kontrolita kaj plilanĝigita per klare mankataj vortoj.
// Ekzemple, troviĝis en ĝi la vorto finnlad-, sed ne finn-; estis filipinoj,
// sed ne filipin-; nord-koreio kaj sud-koreio, sed ne kore- kaj korei-.
//
// Popoldevenaj land-nomoj finiĝantaj per "-lando" (ekz. finnland-, skotland-)
// estis forigitaj, ĉar "lando" estas vorto en la kategorio "tre facila" do la
// popolnomo (finn-, skot-) jam sufiĉas por identigi la vorton. Same estis
// farita al "filipinoj", "bahamoj", ktp.
//
// Pro simila rezonado, la popolnomo jam sufiĉas por la identigo de land-nomoj
// finiĝantaj per "-io". Tamen, ĉar estas propono malpermesi la uzon de "-i-"
// vortomeze, ili estis nur komentitaj. Se iam  vere okazos la malpermeson de
// "-i-" vortomeze, la landnomoj estos facile realdoneblaj.
//
// Plurvortaj landnomoj (kun aŭ sen streko) estis komentitaj dum la sistemo ne
// kapablas rekoni ilin.
var landojKajPopoloj = [
    "afgan-", //"afgani-",
    "alban-", //"albani-",
    "alĝeri-",
    "andor-",
    "angl-", //"angli-",
    "angol-",
    //"antigvo kaj barbudo",
    "arab-",
    "argentin-",
    "armen-", //"armeni-",
    "aŭstrali-",
    "aŭstr-", //"aŭstri-",
    "azerbajĝan-",
    "baham-",
    "bangladeŝ-",
    "barat-",
    "barbad-",
    "barejn-",
    "belg-", //"belgi-",
    "beliz-",
    "belorus-", //"belorusi-",
    "benin-",
    "birm-",
    "bocvan-",
    "bolivi-",
    "bosn-",
    //"bosnio kaj hercegovino",
    "brazil-",
    "brit-", //"briti-",
    "brunej-",
    "bulgar-", //"bulgari-",
    "burkin-",
    "burund-",
    "butan-",
    //"centr-afrik-",
    "ĉad-",
    "ĉeĥ-", //"ĉeĥi-",
    "ĉeĥoslovak-", //"ĉeĥoslovaki-",
    "ĉili-",
    "ĉin-", //"ĉini-",
    "dan-", //"dani-",
    //"demokratia respubliko kongo",
    //"dominika respubliko,
    "dominik-",
    //"ebur-bord-",
    "egipt-", //"egipti-",
    "ekvador-",
    //"ekvatora gvineo",
    "eritre-",
    "eston-", //"estoni-",
    "etiop-", //"etiopi-",
    "fiĝi-",
    "filipin-",
    "finn-",
    "franc-", //"franci-",
    "gabon-",
    "gambi-",
    "gana-",
    "german-", //"germani-",
    "grek-", //"greki-",
    "grenad-",
    "gronland-",
    "gujan-",
    "gvatemal-",
    "gvine-",
    //"gvineo-bisaŭo",
    "ĝibuti-",
    "haiti-",
    "hind-", //"hindi-",
    "hispan-", //"hispani-",
    "hondur-",
    "hungar-", //"hungari-",
    "indonezi-",
    "irak-",
    "iran-",
    "irland-",
    "island-",
    "israel-",
    "ital-", //"itali-",
    "jamajk-",
    "japan-", //"japani-",
    "jemen-",
    "jordani-",
    "jugoslav-", //"jugoslavi-",
    "kaboverd-",
    "kamboĝ-",
    "kamerun-",
    "kanad-",
    "kartvel-", //"kartveli-",
    "katar-",
    "kazaĥ-", //"kazaĥi-",
    "kenj-",
    "kipr-",
    "kirgiz-", //"kirgizi-",
    "kiribat-",
    "kolombi-",
    "komor-",
    "kong-",
    //"kongo brazavila ",
    //"kongo kinŝasa",
    "kore-", //"korei-",
    "kosov-",
    "kostarik-",
    "kroat-", //"kroati-",
    "kub-",
    "kuvajt-",
    "laos-",
    "latv-", //"latvi-",
    "lesot-",
    "liban-",
    "liberi-",
    "libi-",
    "liĥtenŝtejn-",
    "litov-", //"litovi-",
    "luksemburg-",
    "madagaskar-",
    "makedon-", //"makedoni-",
    "malajzi-",
    "malavi-",
    "maldiv-",
    "mali-",
    "malt-",
    "marok-",
    "marŝal-",
    "maŭrici-",
    "maŭritani-",
    "meksik-",
    "mikronezi-",
    "moldav-", //"moldavi-",
    "monak-",
    "mongol-", //"mongoli-",
    "montenegr-",
    "mozambik-",
    "namibi-",
    "naur-",
    "nederland-",
    "nepal-",
    "niĝeri-",
    "niĝer-",
    "nikaragv-",
    //"nord-koreo",
    //"nord-koreio",
    "norveg-", //"norvegi-",
    //"nov-zelando",
    "oman-",
    //"orienta timoro",
    "pakistan-",
    "palaŭ-",
    "panam-",
    //"papuo-nov-gvineo",
    "paragvaj-",
    "peru-",
    "pol-",
    "portugal-", //"portugali-",
    //"respubliko kongo",
    "ruand-",
    "ruman-", //"rumani-",
    "rus-", //"rusi-",
    "salomon-",
    "salvador-",
    "samo-",
    //"sankta kristoforo kaj neviso",
    //"sankta lucio",
    //"sankta vincento kaj grenadinoj",
    "sanmarin-",
    //"santomeo kaj principeo",
    //"sauda arabujo",
    //"sauda arabio",
    "sejŝel-",
    "senegal-",
    "serb-", //"serbi-",
    "siberi-",
    "sieraleon-",
    "singapur-",
    "siri-",
    "skot-",
    "slovak-", //"slovaki-",
    "sloven-", //"sloveni-",
    "somal-", //"somali-",
    "soveti-",
    //"sovet-unio",
    "srilank-",
    //"sud-afriko",
    //"sud-koreujo",
    //"sud-koreio",
    "sudan-",
    "surinam-",
    "svazi-",
    "sved-", //"svedi-",
    "svis-",
    "taĝik-", //"taĝiki-",
    "taj-",
    "tajvan-",
    "tanzani-",
    "togoland-",
    "tong-",
    //"trinidado kaj tobago",
    "tunizi-",
    "turkmen-", //"turkmeni-",
    "turk-", //"turki-",
    "tuval-",
    "ugand-",
    "ukrain-", //"ukraini-",
    //"unuiĝintaj arabaj emirlandoj",
    "urugvaj-",
    "uson-",
    "uzbek-", //"uzbeki-",
    "vanuatu-",
    "vatikan-",
    "venezuel-",
    "vjetnam-", //"vjetnami-",
    "zambi-",
    "zimbabv-",
]

var mondopartoj = [
    "afrik-",
    "amerik-",
    "antarkt-",
    "azi-",
    "eŭrop-",
    "oceani-"
]
