// En la listo enestas du tipoj de vortoj:
//
// - Vortoj finiĝantaj per streketo bezonas vortoklasan finaĵon (-o, -a, -i, -e)
// - Vortoj sen streketoj estas uzeblaj sen finaĵo
//
// La listo de landoj estis unue prenita de la oficiala listo de landnomoj de la
// Akademio de Esperanto (konsltebla sube).
// https://www.akademio-de-esperanto.org/decidoj/landnomoj/listo_de_rekomendataj_landnomoj/
// 
// Poste, ĝi estis kontrolita kaj plilanĝigita per klare mankataj vortoj.
// Ekzemple, troviĝis en ĝi la vorto finnlad-, sed ne finn-; estis filipinoj,
// sed ne filipin-; nord-koreio kaj sud-koreio, sed ne kore- kaj korei-.
var landojKajPopoloj = [
    "afgan-", "afgani-",
    "alban-", "albani-",
    "alĝeri-",
    "andor-",
    "angl-", "angli-",
    "angol-",
    "antigvo kaj barbudo",//kontroli
    "arab-",
    "argentin-",
    "armen-", "armeni-",
    "aŭstrali-",
    "aŭstr-", "aŭstri-",
    "azerbajĝan-",
    "baham-", "bahamoj",
    "bangladeŝ-",
    "barat-",
    "barbad-",
    "barejn-",
    "belg-", "belgi-",
    "beliz-",
    "belorus-", "belorusi-",
    "benin-",
    "birm-",
    "bocvan-",
    "bolivi-",
    "bosn-",
    "bosnio kaj hercegovino",//kontrolu
    "brazil-",
    "brit-", "briti-",
    "brunej-",
    "bulgar-", "bulgari-",
    "burkin-",
    "burund-",
    "butan-",
    "centr-afrik-",//kontrolu
    "ĉad-",
    "ĉeĥ-", "ĉeĥi-",
    "ĉeĥoslovak-", "ĉeĥoslovaki-",
    "ĉili-",
    "ĉin-", "ĉini-",
    "dan-", "dani-",
    "demokratia respubliko kongo",//kontroli
    "dominika respubliko",//kontrolu
    "dominik-",
    "ebur-bord-",//kontrolu
    "egipt-", "egipti-",
    "ekvador-",
    "ekvatora gvineo",//kontrolu
    "eritre-",
    "eston-", "estoni-",
    "etiop-", "etiopi-",
    "fiĝi-",
    "filipin-", "filipinoj",
    "finn-", "finnland-",
    "franc-", "franci-",
    "gabon-",
    "gambi-",
    "gana-",
    "german-", "germani-",
    "grek-", "greki-",
    "grenad-",
    "gronland-",
    "gujan-",
    "gvatemal-",
    "gvine-",
    "gvineo-bisaŭo",//kontrolu
    "ĝibuti-",
    "haiti-",
    "hind-", "hindi-",
    "hispan-", "hispani-",
    "hondur-",
    "hungar-", "hungari-",
    "indonezi-",
    "irak-",
    "iran-",
    "irland-",
    "island-",
    "israel-",
    "ital-", "itali-",
    "jamajk-",
    "japan-", "japani-",
    "jemen-",
    "jordani-",
    "jugoslav-", "jugoslavi-",
    "kaboverd-",
    "kamboĝ-",
    "kamerun-",
    "kanad-",
    "kartvel-", "kartveli-",
    "katar-",
    "kazaĥ-", "kazaĥi-",
    "kenj-",
    "kipr-",
    "kirgiz-", "kirgizi-",
    "kiribat-",
    "kolombi-",
    "komor-", "komoroj",
    "kong-",
    "kongo brazavila ",//kontroli
    "kongo kinŝasa",//kontroli
    "kore-", "korei-",
    "kosov-",
    "kostarik-",
    "kroat-", "kroati-",
    "kub-",
    "kuvajt-",
    "laos-",
    "latv-", "latvi-",
    "lesot-",
    "liban-",
    "liberi-",
    "libi-",
    "liĥtenŝtejn-",
    "litov-", "litovi-",
    "luksemburg-",
    "madagaskar-",
    "makedon-", "makedoni-",
    "malajzi-",
    "malavi-",
    "maldiv-", "maldivoj",
    "mali-",
    "malt-",
    "marok-",
    "marŝal-", "marŝaloj",
    "maŭrici-",
    "maŭritani-",
    "meksik-",
    "mikronezi-",
    "moldav-", "moldavi-",
    "monak-",
    "mongol-", "mongoli-",
    "montenegr-",
    "mozambik-",
    "namibi-",
    "naur-",
    "nederland-",
    "nepal-",
    "niĝeri-",
    "niĝer-",
    "nikaragv-",
    "nord-koreo",//kontroli
    "nord-koreio",//kontroli
    "norveg-", "norvegi-",
    "nov-zelando",//kontroli
    "oman-",
    "orienta timoro",//kontroli
    "pakistan-",
    "palaŭ-",
    "panam-",
    "papuo-nov-gvineo",//kontroli
    "paragvaj-",
    "peru-",
    "pol-", "polland-",
    "portugal-", "portugali-",
    "respubliko kongo",//kontroli
    "ruand-",
    "ruman-", "rumani-",
    "rus-", "rusi-",
    "salomon-", "salomonoj",
    "salvador-",
    "samo-",
    "sankta kristoforo kaj neviso",//kontroli
    "sankta lucio",//kontroli
    "sankta vincento kaj grenadinoj",//kontroli
    "sanmarin-",
    "santomeo kaj principeo",//kontroli
    "sauda arabujo",//kontroli
    "sauda arabio",//kontroli
    "sejŝel-", "sejŝeloj",
    "senegal-",
    "serb-", "serbi-",
    "siberi-",
    "sieraleon-",
    "singapur-",
    "siri-",
    "skot-", "skotland-",
    "slovak-", "slovaki-",
    "sloven-", "sloveni-",
    "somal-", "somali-",
    "soveti-",
    "sovet-unio",//kontroli
    "srilanko",
    "sud-afriko",//kontroli
    "sud-koreujo",//kontroli
    "sud-koreio",//kontroli
    "sudan-",
    "surinam-",
    "svazi-", "svaziland-",
    "sved-", "svedi-",
    "svis-", "svisland-",
    "taĝik-", "taĝiki-",
    "taj-", "tajland-",
    "tajvan-",
    "tanzani-",
    "togoland-",
    "tong-",
    "trinidado kaj tobago",//kontroli
    "tunizi-",
    "turkmen-", "turkmeni-",
    "turk-", "turki-",
    "tuval-",
    "ugand-",
    "ukrain-", "ukraini-",
    "unuiĝintaj arabaj emirlandoj",//kontroli
    "urugvaj-",
    "uson-",
    "uzbek-", "uzbeki-",
    "vanuatu-",
    "vatikan-",
    "venezuel-",
    "vjetnam-", "vjetnami-",
    "zambi-",
    "zimbabv-",
]

var mondopartoj = [
    "afrik-",
    "amerik-",
    "antarkt-",
    "azi-",
    "eŭrop-",
    "oceani-"
]
