// Kopiita el http://remush.be/tezauro/Kontakto.html
//
// Ĉiu vorto en la listo havas "tipon", aŭ 1 aŭ 2.
//
// 1: La vorto estas radiko plus vortoklasa finaĵo (-o, -a, -i, -e).
// 2: La vorto estas "vorteto", uzebla sen finaĵo.
//
// Prefiksoj kaj sufiksoj povus esti en la ĉefa listo laŭ tipo 1, sed
// por konveno ili estas listigitaj en apartaj listoj sube.
var vortaroTreFacilaj = { /* "-a", */
  /* "-aĉ", */
  "aĉeti": 1,
  /* "-ad", */
  "adreso": 1,
  "aero": 1,
  "afero": 1,
  "agi": 1,
  "aĝo": 1,
  /* "-aĵ", */
  "akcepti": 1,
  "akvo": 1,
  "al": 2,
  "alia": 1,
  "alta": 1,
  "ami": 1,
  "amiko": 1,
  /* "-an", */
  "ankaŭ": 2,
  "ankoraŭ": 2,
  "anstataŭ": 2,
  /* "-ant", */
  "antaŭ": 2,
  "aparta": 1,
  "aprilo": 1,
  "apud": 2,
  /* "-ar", */
  "arto": 1,
  "artikolo": 1,
  /* "-as", */
  "asocio": 1,
  /* "-at", */
  "atenta": 1,
  "aŭgusto": 1,
  "baldaŭ": 2,
  "bela": 1,
  "besto": 1,
  "bezoni": 1,
  "bildo": 1,
  "birdo": 1,
  /* "bo-", */
  "bona": 1,
  "brili": 1,
  "celo": 1,
  "cent": 2,
  "certa": 1,
  "ĉambro": 1,
  "ĉar": 2,
  "ĉe": 2,
  "ĉefa": 1,
  "ĉi": 2,
  "ĉia": 2, "ĉian": 2, "ĉiaj": 2, "ĉiajn": 2,
  "ĉiam": 2,
  "ĉie": 2, "ĉien": 2,
  "ĉielo": 1,
  "ĉio": 2, "ĉion": 2,
  "ĉirkaŭ": 2,
  "ĉiu": 2, "ĉiun": 2, "ĉiuj": 2, "ĉiujn": 2,
  "ĉu": 2,
  "da": 2,
  "danki": 1,
  "daŭri": 1,
  "de": 2,
  "decembro": 1,
  "decidi": 1,
  "dek": 2,
  "dekstra": 1,
  "demandi": 1,
  "desegni": 1,
  "devi": 1,
  "deziri": 1,
  "dika": 1,
  "dimanĉo": 1,
  "diri": 1,
  "direkto": 1,
  /* "dis-", */
  "diversa": 1,
  "do": 2,
  "doktoro": 1,
  "dolĉa": 1,
  "domo": 1,
  "dormi": 1,
  "du": 2,
  "dum": 2,
  /* "-e", */
  /* "-ebl", */
  /* "-ec", */
  "eĉ": 2,
  "eduki": 1,
  "edzo": 1,
  /* "-eg", */
  /* "-ej", */
  /* "ek-", */
  "ekster": 2,
  "ekzemplo": 1,
  "ekzisti": 1,
  "el": 2,
  "elekti": 1,
  /* "-em", */
  "en": 2,
  /* "-er", */
  "esperi": 1,
  "esti": 1,
  /* "-estr", */
  /* "-et", */
  "facila": 1,
  "fako": 1,
  "fakto": 1,
  "fali": 1,
  "familio": 1,
  "fari": 1,
  "februaro": 1,
  "feliĉa": 1,
  "fenestro": 1,
  "fermi": 1,
  "festi": 1,
  "filo": 1,
  "filmo": 1,
  "fini": 1,
  "fiŝo": 1,
  "flanko": 1,
  "floro": 1,
  "flugi": 1,
  "fojo": 1,
  "for": 2,
  "forgesi": 1,
  "formo": 1,
  "forta": 1,
  "foti": 1,
  "frapi": 1,
  "frato": 1,
  "frua": 1,
  "funkcio": 1,
  "gazeto": 1,
  /* "ge-", */
  "glaso": 1,
  "granda": 1,
  "grava": 1,
  "grupo": 1,
  "ĝenerala": 1,
  "ĝis": 2,
  "ĝusta": 1,
  "havi": 1,
  "hejmo": 1,
  "helpi": 1,
  "hieraŭ": 2,
  "historio": 1,
  "hodiaŭ": 2,
  "homo": 1,
  "horo": 1,
  /* "-i", */
  "ia": 2, "ian": 2, "iaj": 2, "iajn": 2,
  "iam": 2,
  /* "-id", */
  "ideo": 1,
  "ie": 2, "ien": 2,
  "iel": 2,
  /* "-ig", */
  /* "-iĝ", */
  /* "-il", */
  // "ili": 2,
  /* "-in", */
  /* "-ind", */
  "infano": 1,
  "informi": 1,
  "instrui": 1,
  /* "-int", */
  "inter": 2,
  "interesi": 1,
  "inviti": 1,
  "io": 2, "ion": 2,
  "iri": 1,
  /* "-is", */
  /* "-ism", */
  /* "-ist", */
  /* "-it", */
  "ja": 2,
  "jam": 2,
  "januaro": 1,
  "jaro": 1,
  "ĵaŭdo": 1,
  "je": 2,
  "jen": 2,
  "jes": 2,
  "julio": 1,
  "juna": 1,
  "junio": 1,
  "ĵeti": 1,
  "kaj": 2,
  "kalkuli": 1,
  "kampo": 1,
  "kanti": 1,
  "kapti": 1,
  "kara": 1,
  "kaŭzo": 1,
  "ke": 2,
  "kelka": 1,
  "kia": 2, "kian": 2, "kiaj": 2, "kiajn": 2,
  "kial": 2,
  "kiam": 2,
  "kie": 2, "kien": 2,
  "kiel": 2,
  "kies": 2,
  "kio": 2, "kion": 2,
  "kiom": 2,
  "kiu": 2, "kiun": 2, "kiuj": 2, "kiujn": 2,
  "klara": 1,
  "klaso": 1,
  "klubo": 1,
  "knabo": 1,
  "kolekti": 1,
  "koloro": 1,
  "komenci": 1,
  "komerci": 1,
  "kompreni": 1,
  "komuna": 1,
  "koni": 1,
  "kongreso": 1,
  "konsenti": 1,
  "konsili": 1,
  "konstrui": 1,
  "kontakto": 1,
  "kontenta": 1,
  "kontraŭ": 2,
  "kosti": 1,
  "kredi": 1,
  "krom": 2,
  "kuiri": 1,
  "kulturi": 1,
  "kun": 2,
  "kurso": 1,
  "kuŝi": 1,
  "kvar": 2,
  "kvin": 2,
  "la": 2,
  "labori": 1,
  "lago": 1,
  "lakto": 1,
  "lando": 1,
  "larĝa": 1,
  "lasi": 1,
  "lasta": 1,
  "laŭ": 2,
  "lavi": 1,
  "leciono": 1,
  "legi": 1,
  "lerni": 1,
  "letero": 1,
  "levi": 1,
  // "li": 2,
  "libera": 1,
  "libro": 1,
  "ligi": 1,
  "lingvo": 1,
  "literaturo": 1,
  "loĝi": 1,
  "loko": 1,
  "longa": 1,
  "ludi": 1,
  "lundo": 1,
  "majo": 1,
  /* "mal-", */
  "mano": 1,
  "manĝi": 1,
  "maniero": 1,
  "manki": 1,
  "maro": 1,
  "mardo": 1,
  "marko": 1,
  "marto": 1,
  "maŝino": 1,
  "mateno": 1,
  "mem": 2,
  "membro": 1,
  "memoro": 1,
  "merkredo": 1,
  "meti": 1,
  "metodo": 1,
  "mezo": 1,
  // "mi": 2,
  "mil": 2,
  "miliono": 1,
  "militi": 1,
  "minus": 2,
  "minuto": 1,
  "miri": 1,
  "mono": 1,
  "monato": 1,
  "mondo": 1,
  "monto": 1,
  "montri": 1,
  "morgaŭ": 2,
  "movi": 1,
  "multa": 1,
  "muziko": 1,
  /* "-n", */
  "nacio": 1,
  "naski": 1,
  "naturo": 1,
  "naŭ": 2,
  "ne": 2,
  "necesa": 1,
  "nenia": 2, "nenian": 2, "neniaj": 2, "neniajn": 2,
  "neniam": 2,
  "nenie": 2, "nenien": 2,
  "neniel": 2,
  "nenio": 2, "nenion": 2,
  "ni": 2,
  "nokto": 1,
  "nomo": 1,
  "nova": 1,
  "novembro": 1,
  "nulo": 1,
  "numero": 1,
  "nun": 2,
  "nur": 2,
  /* "-o", */
  /* "-obl", */
  "ofico": 1,
  "ofte": 1,
  "ok": 2,
  "okazi": 1,
  "oktobro": 1,
  "okupi": 1,
  "ol": 2,
  /* "-on", */
  "oni": 2,
  /* "-ont", */
  "opinio": 1,
  "ordinara": 1,
  "organizi": 1,
  /* "-os", */
  /* "-ot", */
  "pagi": 1,
  "paĝo": 1,
  "pano": 1,
  "papero": 1,
  "pardoni": 1,
  "paroli": 1,
  "parto": 1,
  "patro": 1,
  "peco": 1,
  "pendi": 1,
  "pensi": 1,
  "per": 2,
  "perdi": 1,
  "permesi": 1,
  "persono": 1,
  "peti": 1,
  "piedo": 1,
  "plaĉi": 1,
  "plej": 2,
  "plena": 1,
  "plezuro": 1,
  "pli": 2,
  "plu": 2,
  "pluraj": 1,
  "poemo": 1,
  "popolo": 1,
  "por": 2,
  "pordo": 1,
  "porti": 1,
  "post": 2,
  "poŝto": 1,
  "povi": 1,
  "precipe": 1,
  "preferi": 1,
  "preni": 1,
  "prepari": 1,
  "presi": 1,
  "preskaŭ": 2,
  "preta": 1,
  "prezenti": 1,
  "prezidi": 1,
  "pri": 2,
  "printempo": 1,
  "pro": 2,
  "problemo": 1,
  "produkti": 1,
  "proksima": 1,
  "propra": 1,
  "provi": 1,
  "publiko": 1,
  "pura": 1,
  "radio": 1,
  "rajto": 1,
  "rakonti": 1,
  "rapida": 1,
  "raporti": 1,
  /* "re-", */
  "redakti": 1,
  "regiono": 1,
  "regulo": 1,
  "rekomendi": 1,
  "renkonti": 1,
  "respondi": 1,
  "resti": 1,
  "revuo": 1,
  "ricevi": 1,
  "riĉa": 1,
  "ridi": 1,
  "rigardi": 1,
  "rilati": 1,
  "rimarki": 1,
  "ripeti": 1,
  "rivero": 1,
  "rompi": 1,
  "sabato": 1,
  "salono": 1,
  "saluti": 1,
  "sana": 1,
  "scii": 1,
  "scienco": 1,
  "se": 2,
  "sed": 2,
  "seĝo": 1,
  "sekvi": 1,
  "semajno": 1,
  "sen": 2,
  "sendi": 1,
  "senti": 1,
  "sep": 2,
  "septembro": 1,
  "serĉi": 1,
  "servi": 1,
  "ses": 2,
  "si": 2,
  "sidi": 1,
  "signifi": 1,
  "simila": 1,
  "simpla": 1,
  "sinjoro": 1,
  "situacio": 1,
  "skatolo": 1,
  "skribi": 1,
  "sola": 1,
  "somero": 1,
  "soni": 1,
  "speciala": 1,
  "sperta": 1,
  "sporto": 1,
  "stacio": 1,
  "stari": 1,
  "strato": 1,
  "studi": 1,
  "sub": 2,
  "sufiĉa": 1,
  "sukcesi": 1,
  "suno": 1,
  "super": 2,
  "supre": 1,
  "sur": 2,
  "ŝajni": 1,
  "ŝanĝi": 1,
  "ŝati": 1,
  // "ŝi": 2,
  "ŝipo": 1,
  "ŝranko": 1,
  "ŝtato": 1,
  "tablo": 1,
  "tago": 1,
  "tamen": 2,
  "teatro": 1,
  "telefono": 1,
  "televido": 1,
  "temo": 1,
  "tempo": 1,
  "teni": 1,
  "tero": 1,
  "tia": 2, "tian": 2, "tiaj": 2, "tiajn": 2,
  "tial": 2,
  "tiam": 2,
  "tie": 2, "tien": 2,
  "tiel": 2,
  "ties": 2,
  "tiom": 2,
  "timi": 1,
  "tio": 2, "tion": 2,
  "tiu": 2, "tiun": 2, "tiuj": 2, "tiujn": 2,
  "tra": 2,
  "traduki": 1,
  "tranĉi": 1,
  "trans": 2,
  "tre": 2,
  "tri": 2,
  "trinki": 1,
  "tro": 2,
  "trovi": 1,
  "tuj": 2,
  "tuta": 1,
  /* "-u", */
  /* "-uj", */
  /* "-ul", */
  /* "-um", */
  "universala": 1,
  "universitato": 1,
  "unu": 2,
  "urbo": 1,
  "utila": 1,
  /* "-us", */
  "uzi": 1,
  "vagono": 1,
  "valoro": 1,
  "varma": 1,
  "veni": 1,
  "vendi": 1,
  "vendredo": 1,
  "vera": 1,
  "verki": 1,
  "vespero": 1,
  "vesto": 1,
  "veturi": 1,
  // "vi": 2,
  "viando": 1,
  "vidi": 1,
  "vilaĝo": 1,
  "vintro": 1,
  "viro": 1,
  "viziti": 1,
  "vojo": 1,
  "vojaĝi": 1,
  "voli": 1,
  "vorto": 1,
  "zorgi": 1,
};

var personajPronomoj = [
    "mi",
    "vi",
    "li",
    "ŝi",
    // "ĝi" ne aperas en la listo de mil vortoj. Ĉu intence?
    // "ĝi",
    "ni",
    "ili",
];

var prefiksojTreFacilaj = [ "bo",
  "dis",
  "ek",
  "ge",
  "mal",
  "re",
];

var sufiksojTreFacilaj = [// "a",
  "aĉ",
  "ad",
  "aĵ",
  "an",
  // "ant", (participo, ne por "tre facila")
  "ar",
  // "as",
  // "at", (participo)
  // "e",
  "ebl",
  "ec",
  "eg",
  "ej",
  "em",
  "er",
  "estr",
  "et",
  // "i",
  "id",
  "ig",
  "iĝ",
  "il",
  "in",
  "ind",
  // "int", (participo)
  "is",
  "ism",
  "ist",
  // "it", (participo)
  // "n",
  // "o",
  "obl",
  "on",
  // "ont", (participo)
  "os",
  // "ot", (participo)
  // "u",
  "uj",
  "ul",
  "um",
  // "us",

  // participaj finaĵoj:
  "ant",
  "at",
  "int",
  "it",
  "ont",
  "ot",

];
